base_model: NousResearch/Meta-Llama-3.1-8B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

datasets:
  # - path: tatsu-lab/alpaca
  #   type: alpaca
  - path: vietgpt/news_summarization_vi  # duongttr/vi-dataset-for-pretrain
    split: train
    field: content
    type: completion
    trust_remote_code: true
    streaming: true
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./outputs/out

sequence_len: 8192
sample_packing: true


wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 100
evals_per_epoch: 2
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:
  pad_token: <|end_of_text|>

fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_sharding_strategy: 1
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_sync_module_states: true
  fsdp_cpu_ram_efficient_loading: true
  fsdp_use_orig_params: true
  fsdp_offload_params: false

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config