# compute_environment: LOCAL_MACHINE
# debug: false
# distributed_type: FSDP
# downcast_bf16: 'no'
# fsdp_config:
#   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
#   fsdp_backward_prefetch: BACKWARD_PRE
#   fsdp_cpu_ram_efficient_loading: true
#   fsdp_forward_prefetch: false
#   fsdp_limit_all_gathers: true
#   fsdp_offload_params: true
#   fsdp_sharding_strategy: FULL_SHARD
#   fsdp_state_dict_type: FULL_STATE_DICT
#   fsdp_sync_module_states: true
#   fsdp_transformer_layer_cls_to_wrap: Qwen3MoeDecoderLayer
#   fsdp_use_orig_params: false
# machine_rank: 0
# main_training_function: main
# mixed_precision: 'bf16'
# num_machines: 1
# num_processes: 4
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  offload_optimizer_device: none
  offload_param_device: none
  bf16:
    enabled: true  # Đảm bảo format đúng
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
